name: Build & Package

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential dialog dpkg-dev

    - name: Build binary
      run: |
        make
        mkdir -p output
        cp build/modbus-monitor output/

    - name: Create DEB package
      run: |
        make deb
        mkdir -p output
        cp build/*.deb output/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.0.2
      with:
        name: yamada-build-artifacts
        path: output/
